title: Learn by doing: the art of self-taughting
author: Mariana9420
email: marianabelenluduena@gmail.com
description: Ever heard of Learn by doing? Find out here!
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
